<?php

namespace App\Models;

use App\Models\Concerns\BelongsToOrganization;
use Database\Factories\ApiKeyFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * An organization's credential for external integrations. The secret itself is
 * never stored: only its SHA-256 (secret_hash), which is never serialized.
 */
class ApiKey extends Model
{
    /** @use HasFactory<ApiKeyFactory> */
    use BelongsToOrganization, HasFactory, HasUuids;

    /**
     * prefix and secret_hash are generated by the server and are not mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'expires_at',
    ];

    /**
     * @var list<string>
     */
    protected $hidden = [
        'secret_hash',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'last_used_at' => 'datetime',
            'expires_at' => 'datetime',
            'revoked_at' => 'datetime',
        ];
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    /**
     * @return HasMany<Transaction, $this>
     */
    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }
}
