<?php

namespace App\Models;

use App\Models\Concerns\BelongsToOrganization;
use Database\Factories\ApiKeyFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * An organization's credential for external integrations. The secret itself is
 * never stored: only its SHA-256 (secret_hash), which is never serialized.
 */
class ApiKey extends Model
{
    /** @use HasFactory<ApiKeyFactory> */
    use BelongsToOrganization, HasFactory, HasUuids;

    public const STATUS_ACTIVE = 'active';

    public const STATUS_REVOKED = 'revoked';

    public const STATUS_EXPIRED = 'expired';

    public const MAX_ACTIVE_PER_ORGANIZATION = 10;

    /**
     * last_used_at is written at most once per this many seconds per key, not on every request.
     */
    public const LAST_USED_RESOLUTION_SECONDS = 60;

    /**
     * prefix and secret_hash are generated by the server and are not mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'expires_at',
    ];

    /**
     * @var list<string>
     */
    protected $hidden = [
        'secret_hash',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'last_used_at' => 'datetime',
            'expires_at' => 'datetime',
            'revoked_at' => 'datetime',
        ];
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    /**
     * @return HasMany<Transaction, $this>
     */
    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Keys that authenticate right now: not revoked and not expired.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query
            ->whereNull($this->qualifyColumn('revoked_at'))
            ->where(fn (Builder $query) => $query
                ->whereNull($this->qualifyColumn('expires_at'))
                ->orWhere($this->qualifyColumn('expires_at'), '>', now()));
    }

    public function isRevoked(): bool
    {
        return $this->revoked_at !== null;
    }

    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->lte(now());
    }

    public function status(): string
    {
        return match (true) {
            $this->isRevoked() => self::STATUS_REVOKED,
            $this->isExpired() => self::STATUS_EXPIRED,
            default => self::STATUS_ACTIVE,
        };
    }

    /**
     * Idempotent: revoking an already revoked key keeps the original revoked_at.
     */
    public function revoke(): void
    {
        if ($this->isRevoked()) {
            return;
        }

        $this->forceFill(['revoked_at' => now()])->save();
    }

    /**
     * Skips the write when the key was already marked as used within the resolution window.
     */
    public function recordUsage(): void
    {
        $now = now();

        if ($this->last_used_at !== null && $this->last_used_at->gt($now->copy()->subSeconds(self::LAST_USED_RESOLUTION_SECONDS))) {
            return;
        }

        // Through the base query so updated_at keeps meaning "the key's settings changed".
        $this->newQuery()->whereKey($this->getKey())->toBase()->update(['last_used_at' => $now]);
        $this->forceFill(['last_used_at' => $now])->syncOriginalAttribute('last_used_at');
    }
}
