<?php

namespace App\Http\Requests\Product;

use App\Enums\ProductStatus;
use App\Support\CurrentOrganization;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * The SKU uniqueness check includes soft-deleted products, matching the
     * unique (organization_id, sku) index.
     *
     * @return array<string, list<mixed>>
     */
    public function rules(CurrentOrganization $current): array
    {
        return [
            'id' => ['prohibited'],
            'organization_id' => ['prohibited'],
            'name' => ['required', 'string', 'max:255'],
            'sku' => [
                'nullable',
                'string',
                'max:64',
                Rule::unique('products', 'sku')->where('organization_id', $current->organization->id),
            ],
            'price' => ['required', 'numeric', 'decimal:0,2', 'min:0', 'max:9999999999.99'],
            'status' => ['sometimes', Rule::enum(ProductStatus::class)],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'id.prohibited' => 'The id is generated by the server.',
            'organization_id.prohibited' => 'The organization is taken from the X-Organization-Id context and cannot be set in the payload.',
            'sku.unique' => 'This SKU is already used by another product in this organization, including deleted products.',
        ];
    }
}
