<?php

namespace App\Http\Requests\Customer;

use App\Support\CurrentOrganization;
use App\Support\ExternalId;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class StoreCustomerRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        if (is_string($this->input('email'))) {
            $this->merge(['email' => Str::lower($this->input('email'))]);
        }
    }

    /**
     * The email and external id uniqueness checks include soft-deleted customers, matching the
     * unique (organization_id, email) and (organization_id, external_id) indexes.
     *
     * @return array<string, list<mixed>>
     */
    public function rules(CurrentOrganization $current): array
    {
        return [
            'id' => ['prohibited'],
            'organization_id' => ['prohibited'],
            'name' => ['required', 'string', 'max:255'],
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                Rule::unique('customers', 'email')->where('organization_id', $current->organization->id),
            ],
            'external_id' => [
                'nullable',
                ...ExternalId::rules(),
                Rule::unique('customers', 'external_id')->where('organization_id', $current->organization->id),
            ],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'id.prohibited' => 'The id is generated by the server.',
            'organization_id.prohibited' => 'The organization is taken from the X-Organization-Id context and cannot be set in the payload.',
            'email.unique' => 'This email is already used by another customer in this organization, including deleted customers.',
            'external_id.regex' => 'The external id may only contain letters, numbers, dots, underscores, colons and hyphens.',
            'external_id.unique' => 'This external id is already used by another customer in this organization, including deleted customers.',
        ];
    }
}
