<?php

namespace App\Http\Requests\ApiKey;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreApiKeyRequest extends FormRequest
{
    /**
     * Expiration options in days; null (or omitted) means the key does not expire.
     */
    public const EXPIRATION_OPTIONS = [30, 90, 365];

    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, list<mixed>>
     */
    public function rules(): array
    {
        return [
            'organization_id' => ['prohibited'],
            'prefix' => ['prohibited'],
            'secret_hash' => ['prohibited'],
            'name' => ['required', 'string', 'max:100'],
            'expires_in_days' => ['nullable', 'integer', Rule::in(self::EXPIRATION_OPTIONS)],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'organization_id.prohibited' => 'The organization is taken from the X-Organization-Id context and cannot be set in the payload.',
            'prefix.prohibited' => 'The key is generated by the server.',
            'secret_hash.prohibited' => 'The key is generated by the server.',
            'expires_in_days.in' => 'The expiration must be 30, 90 or 365 days, or null for a key that does not expire.',
        ];
    }

    public function expiresInDays(): ?int
    {
        $days = $this->validated('expires_in_days');

        return $days === null ? null : (int) $days;
    }
}
